export const BADGES = [
  {
    id: "first_goal",
    name: "First Step",
    description: "Completed your first academic goal!",
    icon: "🎯",
    tier: "bronze",
    type: "goals_completed",
    threshold: 1,
  },
  {
    id: "streak_7",
    name: "7-Day Ignition",
    description: "Maintained a 7-day study streak",
    icon: "⚡",
    tier: "bronze",
    type: "streak",
    threshold: 7,
  },
  {
    id: "streak_30",
    name: "30-Day Scholar",
    description: "Maintained a 30-day study streak! 1 Month of consistency.",
    icon: "🥉",
    tier: "silver",
    type: "streak",
    threshold: 30,
  },
  {
    id: "streak_60",
    name: "60-Day Titan",
    description: "Maintained a 60-day study streak! 2 Months strong.",
    icon: "🥈",
    tier: "silver",
    type: "streak",
    threshold: 60,
  },
  {
    id: "streak_90",
    name: "90-Day Master",
    description: "Maintained a 90-day study streak! 3 Months of relentless focus.",
    icon: "🥇",
    tier: "gold",
    type: "streak",
    threshold: 90,
  },
  {
    id: "streak_120",
    name: "120-Day Legend",
    description: "Maintained a 120-day study streak! 4 Months of mastery.",
    icon: "💎",
    tier: "platinum",
    type: "streak",
    threshold: 120,
  },
  {
    id: "streak_365",
    name: "365-Day Immortal",
    description: "A full year of uninterrupted study dedication!",
    icon: "👑",
    tier: "diamond",
    type: "streak",
    threshold: 365,
  },
  {
    id: "hours_10",
    name: "Deep Focus",
    description: "Completed 10 hours (600 mins) of focused academic study",
    icon: "⏱️",
    tier: "bronze",
    type: "minutes",
    threshold: 600,
  },
  {
    id: "hours_50",
    name: "Century Scholar",
    description: "Completed 50 hours (3000 mins) of focused academic study",
    icon: "🚀",
    tier: "gold",
    type: "minutes",
    threshold: 3000,
  },
];
